/* ============================================================
   YOUR SITE'S CONTENT
   Generated by admin.html. Change the text between quotes,
   save, refresh the page.
   ============================================================ */

window.SITE_CONTENT = {
  nav: {
    logo: "Mohammed Essam",
    role: "copywriter",
    tagline: "",
    badge: "available for work"
  },
  ticket: {
    name: "MOHAMMED ESSAM",
    band: "If I play, I play to win",
    game: "A red-tier ticket to the mind of",
    serial: "No. 131313 . Exp. never",
    titleTop: "Award-losing",
    titleBottom: "copywriter",
    sub: "I write in English and Arabic. I order coffee in Spanish and French.",
    scratchNote: "That for a ticket to win, had to bought first",
    badge: "Won nothing",
    terms: "Odds of winning: historically High. Ticket has no cash value and neither did the awards. Keep this as proof of participation or share it with your loved ones.",
    stampArc: "Time is a timeless joke",
    stampName: "As seen on TV",
    stampValue: "",
    stampFoot: "",
    stampPhoto: "portrait-rooftop.jpg",
    stampUrl: "https://open.spotify.com/playlist/3LBELz6m3BsYudI8OQar6B",
    awards: [],
    wonBand: "The National Award Lottery",
    wonTitleTop: "Award-winning",
    wonTitleBottom: "copywriter",
    wonBadge: "Correction notice",
    wonLine: "We regret to inform you the joke is over.",
    wonStampArc: "Time is a timeless joke",
    nav: [
      {
        label: "WORK",
        num: "01",
        url: "work.html"
      },
      {
        label: "WORK THAT WORKED",
        num: "02",
        url: "about.html"
      },
      {
        label: "Hire me?",
        num: "03",
        url: "mailto:m22essam@gmail.com",
        "scratch": true,
        scratchHint: "Scratch to reveal"
      }
    ]
  },
  jokes: {
    tabAway: "Fine, go. I'll wait.",
    footer: "No copywriters reserved. ",
    console: "You really opened the console on a copywriter's site? yes, it's vibe coded, happy now?",
    notFound: "Go stretch your back or go home. ",
    emptyWork: "Nothing here yet. Give it a minute.",
    nextLabel: "Keep going"
  },
  work: {
    heading: "The work.",
    note: "Some are real. Some are spec. None of them are in Japanese.",
    producedLabel: "Produced",
    presentedLabel: "Spec",
    limit: 0,
    projects: [
      {
        slug: "yango-unstoppable-rides",
        title: "Unstoppable Rides",
        client: "Yango",
        category: "Film",
        year: "2025",
        image: "live/yango-move-smart-move-smooth-cover.jpg",
        alt: "Yango, Unstoppable Rides",
        sticker: "Three films, three markets",
        tagline: "A super app for a city that is not on your side.",
        story: [
          "Sometimes the city is not in your favour, especially when you are in a rush or sticking to a budget. The Yango super app has an answer for each of those.",
          "Three films: The Wedding Rush and No-Haggle No-Worries for Pakistan, One-Super-Tap for Oman."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/2AqNp6vwRky/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Pakistan: The Wedding Rush"
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/HWFdXqbduWe/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Oman: One-Super-Tap"
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/HU9Uy-NJbzM/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Pakistan: No-Haggle, No-Worries"
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Global creative lead",
            name: "Nikita Nikiforov"
          },
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Art director",
            name: "Hassan AB"
          },
          {
            role: "Super app art director",
            name: "Dmitry Vershinin"
          },
          {
            role: "Producer",
            name: "Evgeniia Sabirzianova"
          },
          {
            role: "Production lead",
            name: "Olesia Starodubtseva"
          },
          {
            role: "Brand director",
            name: "Viktoria Nikulnikova"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "pringles-champions-of-fun",
        title: "Champions of Fun",
        client: "Pringles",
        category: "Film",
        year: "2024",
        image: "live/pringles-arabia-champions-of-fun-ft-david-vila-cover.jpg",
        alt: "Pringles, Champions of Fun",
        sticker: "Ft. David Villa",
        tagline: "A transfer announcement, for fun.",
        story: [
          "Football has got a bit too tactical. Pringles wanted it fun again.",
          "With every headline about players moving to the Saudi League, we staged a press conference where David Villa announced he was heading to Saudi Arabia to bring fun back to football."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/Hz6kx3fUPrX/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/-YpNaC-uYJp/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/QMcPv27-gfa/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/SHZUgP9SsQ5/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/8g88kBNAEE4/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Client",
            name: "Pringles"
          },
          {
            role: "Agency",
            name: "Socialize"
          },
          {
            role: "Creative director",
            name: "Jason Velazquez"
          },
          {
            role: "Copywriters",
            name: "Jack Rogers, Mohammed Essam"
          },
          {
            role: "Art director",
            name: "James Young"
          },
          {
            role: "Account director",
            name: "Rhea Samuel"
          },
          {
            role: "Account managers",
            name: "Mo Awkel, Marwa Elkhateeb"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "rivan-tower",
        title: "The Hotel Is Yours",
        client: "Rivan Tower",
        category: "Film",
        year: "2023",
        image: "live/rivan-tower-cover.jpg",
        alt: "Rivan Tower, The Hotel Is Yours",
        sticker: "Sold out in a week",
        tagline: "Own the room, do not rent it.",
        story: [
          "Rivan Tower wanted to change how Egyptians see hotels: own the room instead of renting it.",
          "We cast Bayoumi Fouad and shot a comedy film in two days that treated hotel living as a permanent address rather than a holiday.",
          "The entire tower sold out within a week."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/QP3a6A_8ZBQ/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Written and directed by",
            name: "Mohammed Essam"
          },
          {
            role: "Creative strategist",
            name: "Aya El-Hadad"
          },
          {
            role: "DOP",
            name: "Haitham Nasser"
          },
          {
            role: "Editor and colorist",
            name: "Donia Sallam"
          },
          {
            role: "Motion graphics",
            name: "Ahmad Mokhtar, Omar Abdelmonem"
          },
          {
            role: "Account director",
            name: "Dina Abuel-Magd"
          },
          {
            role: "Production",
            name: "Mohamed Gharieb, Mahmoud Gharieb, Osama Nakeeb"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "true-colors-of-dominos",
        title: "The True Colors",
        client: "Domino's",
        category: "Miami Ad School",
        year: "2026",
        image: "Minimalist Elegant Modern Bold  Advertising Poster Design _ Coffee Shop Branding.jpg",
        alt: "Domino's making the streets safer",
        sticker: "Never left the deck",
        tagline: "Billboards that hear you walking home.",
        story: [
          "Walking home at night in heels should not be frightening. To help women feel safer on the streets of London, Domino's showed the city its true colors with slicing-edge OOH billboards using audio-recognition technology. The billboards pick up the sound of accelerating high heels and flash intense red and blue, mimicking a police siren to scare off anyone thinking of causing trouble."
        ],
        media: [
          {
            type: "image",
            src: "Dominos art board.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "Dominos art style .jpg",
            caption: "",
            layout: "full"
          },
          {
            type: "video",
            src: "<div style=\"padding:56.25% 0 0 0;position:relative;\"><iframe src=\"https://player.vimeo.com/video/1205222256?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" style=\"position:absolute;top:0;left:0;width:100%;height:100%;\" title=\"Dominos - The True Color\"></iframe></div>",
            caption: ""
          },
          {
            type: "image",
            src: "dominos bus stop poster mockup.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "Dominos news.jpg",
            caption: "",
            layout: "half"
          }
        ],
        credits: [
          {
            role: "Team",
            name: "Mohammed Essam, Baltazar Lee"
          },
          {
            role: "Tutor",
            name: "Pranay Suri"
          },
          {
            role: "Client",
            name: "Domino's, Miami Ad School Madrid"
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "pop-the-pressure",
        title: "Pop the Pressure",
        client: "Tuborg",
        category: "D&AD brief",
        year: "2026",
        image: "Tuborg poster on poster.jpg",
        alt: "Tuborg Pop the Pressure",
        sticker: "D&AD brief",
        tagline: "Thousands of balloons, one Glastonbury set.",
        story: [
          "Rising depression and anxiety are holding London's youth back.",
          "To release the pressure, Tuborg ran a symbolic activation at Glastonbury. During a set by Dave, fans popped thousands of balloons standing in for real struggles, to feel lighter, see clearer and party responsibly."
        ],
        media: [
          {
            type: "image",
            src: "Tuborg caseboard.jpg",
            caption: ""
          },
          {
            type: "video",
            src: "<div style=\"padding:55.21% 0 0 0;position:relative;\"><iframe src=\"https://player.vimeo.com/video/1218494179?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" style=\"position:absolute;top:0;left:0;width:100%;height:100%;\" title=\"Tuborg - Pop The Pressure\"></iframe></div>",
            caption: ""
          },
          {
            type: "image",
            src: "Tuborg Poster Mockup 44.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "Tuborg poster on poster.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "Tuborg wall  mockup.png",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "tuborg tote.jpg",
            caption: "",
            layout: "half"
          }
        ],
        credits: [
          {
            role: "Team",
            name: "Mohammed Essam, Baltazar Lee, Ana Molinero"
          },
          {
            role: "Tutor",
            name: "Pranay Suri"
          },
          {
            role: "Client",
            name: "Tuborg for D&AD, Miami Ad School Madrid"
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "pringles-cheesy-cheese",
        title: "Cheesy Cheese",
        client: "Pringles Arabia",
        category: "Film",
        year: "2023",
        image: "live/pringles-arabia-cheesy-cheese-cover.jpg",
        alt: "Pringles Arabia, Cheesy Cheese",
        sticker: "Cheese ad, no cheese",
        tagline: "A cheese pun with the cheese legally removed.",
        story: [
          "Pringles launched its Deli range in a region that loves bold flavour, but faced a legal restriction: no saying cheese in Arabic.",
          "So we built the whole commercial on a couple so taken with the flavour that they start hallucinating, and let the laughs and the nonsense carry the taste instead of the word."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/Fqoa4rIC3su/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/I2Dv8Adn5NA/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriters",
            name: "Jack Rogers, Mohammed Essam"
          },
          {
            role: "Creative director",
            name: "Jason Velasquez Burayag"
          },
          {
            role: "Account manager",
            name: "Mohamed Awkal"
          },
          {
            role: "Account executive",
            name: "Rahim"
          },
          {
            role: "Agency",
            name: "Socialize, We Are Social"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "afg-skybridge",
        title: "5-Star Investment",
        client: "AFG Skybridge",
        category: "Film",
        year: "2023",
        image: "live/skybridge-cover.jpg",
        alt: "AFG Skybridge, 5-Star Investment",
        sticker: "Cairo's first branded residences",
        tagline: "Have your cake and live in it.",
        story: [
          "Skybridge Tower brought Cairo its first branded residences attached to a hotel.",
          "Our campaign, Have your cake and live in it, was built to get cautious investors comfortable with property. We kept the visuals rich and the tone relaxed, and let the numbers do the arguing."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/AD-9zoaBeNQ/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Creative team",
            name: "Aya Elhaddad, Mohammed Essam"
          },
          {
            role: "Director",
            name: "Omar Shawky"
          },
          {
            role: "Account managers",
            name: "Nancy Nabil, Esraa Moharam"
          },
          {
            role: "Production house",
            name: "Cameo Productions"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "song-for-the-cashless",
        title: "A Song for the Cashless",
        client: "Social Nuts",
        category: "Music",
        year: "2022",
        image: "live/cah-less-not-even-a-problem-cover.jpg",
        alt: "Social Nuts, A Song for the Cashless",
        sticker: "Mama! I wrote a song",
        tagline: "Broke, but rich in the head.",
        story: [
          "Egypt's unstable currency has put a lot of people under financial stress, and money-saving tips are not much help when there is no money to save.",
          "So instead of saving, we sold imagination. Feha Cash, with a track by MTM and Abo El-Anwar, made the case that joy does not wait for wealth if you are already living like a millionaire in your head."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/2VoVktanSg6/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/2SNMDG_q6Ma/embed?bgcolor=%23bebebe&autohide=false&lazyLoading=true&maxframewidth=6400&maxframeheight=75&api_key=BehancePro2View",
            caption: "Audio only"
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Idea",
            name: "Mohammed Essam, Aya ElHaddad"
          },
          {
            role: "Lyrics",
            name: "Mohammed Essam, Abo El-Anwar"
          },
          {
            role: "Featuring",
            name: "MTM, Abo El-Anwar"
          },
          {
            role: "Music",
            name: "Ahmed Tarek Yahia"
          },
          {
            role: "Art direction",
            name: "Hossam Shebl, Mostafa Shokry, Ahmed Mokhtar"
          },
          {
            role: "Art team",
            name: "Ahmad Zaawel, Zeina ElBakry, Nada Khaled"
          },
          {
            role: "Motion graphics lead",
            name: "Ahmad Mokhtar"
          },
          {
            role: "Motion graphics",
            name: "Omar Moneam, Rahma Mahmoud, Mahmoud Gammal"
          },
          {
            role: "Special thanks",
            name: "Youssef Nagi"
          },
          {
            role: "Client",
            name: "Social Nuts"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "quarantine-games",
        title: "The Quarantine Games",
        client: "Social Nuts",
        category: "Game",
        year: "2020",
        image: "live/the-quarantine-game-bnk-alhthr-cover.gif",
        alt: "Social Nuts, The Quarantine Games",
        sticker: "Played for charity",
        tagline: "Monopoly, but the year is 2020.",
        story: [
          "We made Bank El Hazr, The Curfew Bank, a wordplay on the Egyptian version of Monopoly that everyone grew up playing.",
          "It was built to entertain people through lockdown and raise money at the same time. For every person who played, we donated to one of four causes: day-to-day workers, animal shelters taking in pets people gave up out of fear of infection, homeless children, and connecting seniors in care homes with their families."
        ],
        media: [
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-01.gif",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-02.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-03.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-04.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-05.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-06.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-07.gif",
            caption: ""
          },
          {
            type: "image",
            src: "live/the-quarantine-game-bnk-alhthr-08.jpg",
            caption: ""
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam, Aya Elhaddad"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          },
          {
            role: "Art Director",
            name: "Mahmoud Tammam"
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "momtaz-cement-chronicles",
        title: "The Chronicles",
        client: "Momtaz Cement",
        category: "Ramadan campaign",
        year: "2023",
        image: "live/al-momtaz-chronicals-cover.jpg",
        alt: "Momtaz Cement, The Chronicles",
        sticker: "Ramadan, as a cement brand",
        tagline: "Three riddles, three villages, one bag of cement.",
        story: [
          "Getting into the Ramadan competition in Egypt as a cement brand is hard. Most people reach for lighter brands that month, so we went the other way.",
          "We told the message in a folkloric style: three riddles set in three Egyptian villages, each one solved with a Momtaz Cement product.",
          "We built them in layers, and people received them in a concentrated way."
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/FaREsotpM9X/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Story 1: The knight who made his way through the crack of dawn"
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/KEDtbxxGukg/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Story 2: The witch who saw the village flooded twice"
          },
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/QZDKxyFqdqS/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: "Story 3: Seven omens leading to the end"
          },
          {
            type: "image",
            src: "live/al-momtaz-chronicals-01.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Creative strategist",
            name: "Aya Haddad"
          },
          {
            role: "Art director",
            name: "Mahmoud Tammam"
          },
          {
            role: "Account manager",
            name: "Mansour Salem"
          },
          {
            role: "Illustrator",
            name: "Hosam Shebl"
          },
          {
            role: "Lead motion designer",
            name: "Ahmed Mokhtar"
          },
          {
            role: "Senior graphic designer",
            name: "Nada Khalid"
          },
          {
            role: "Senior motion designer",
            name: "Omar Abdelmoneim"
          },
          {
            role: "Motion designer",
            name: "Rahma Mahmoud"
          },
          {
            role: "Graphic designer",
            name: "Ahmed Zaweel"
          },
          {
            role: "Digital advertiser",
            name: "Mohamed Hassan"
          },
          {
            role: "Music and sound design",
            name: "Rafik Ragy"
          },
          {
            role: "Vocals",
            name: "Dalia Samir, Mohab Ragab"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "modon-actors-too-seriously",
        title: "Sometimes, Actors Take It Too Seriously",
        client: "Modon",
        category: "Film",
        year: "2023",
        image: "live/modon-developments-cover.jpg",
        alt: "Modon, Sometimes, Actors Take It Too Seriously",
        sticker: "I wrote it and directed it",
        tagline: "Method acting, applied to real estate.",
        story: [
          "Sometimes actors take their roles too seriously. Sayed Ragab bought a serviced apartment to get into the hotel owner mindset for his next gig.",
          "I wrote and directed this for Modon Developments, showing a hotel where you do not just stay, you own the room and rent it out when you are not in it.",
          "As a tribute to Tommy Wiseau, I cut a director's fun version: vimeo.com/525523825"
        ],
        media: [
          {
            type: "video",
            src: "https://www-ccv.adobe.io/v1/player/ccv/DyYbX8i6f_f/embed?bgcolor=%23191919&lazyLoading=true&api_key=BehancePro2View",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Wrote and directed",
            name: "Mohammed Essam"
          },
          {
            role: "Creative",
            name: "Mohammed Essam, Aya El Haddad"
          },
          {
            role: "Account director",
            name: "Dina Ibrahim"
          },
          {
            role: "DOP",
            name: "Haitham Nassar"
          },
          {
            role: "Editor and colorist",
            name: "Donia Salam"
          },
          {
            role: "VFX",
            name: "Ahmad Mokhtar, Omar Abdelmoneim"
          },
          {
            role: "Producers",
            name: "Rania Mekki, Shireen Diab"
          },
          {
            role: "Stylist",
            name: "Ola Ashraaf"
          },
          {
            role: "Motion graphics",
            name: "Rahma Mohamed"
          },
          {
            role: "Art director",
            name: "Mohamed Ahmed Nasr"
          },
          {
            role: "Art direction team",
            name: "Mohamed Taha, Nour Moheb, Mai Mahros, Nour Mohamed"
          },
          {
            role: "Prop master",
            name: "Mahmoud Taima"
          },
          {
            role: "Production manager",
            name: "Ziad Magdy"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "red-expo-got-the-keys",
        title: "You Got the Keys",
        client: "RED",
        category: "Jingle",
        year: "2024",
        image: "live/red-expo-jingle-ad-cover.jpg",
        alt: "RED, You Got the Keys",
        sticker: "It rhymed",
        tagline: "Stop borrowing the chalet.",
        story: [
          "RED, founded in 2020, came into a crowded Egyptian real estate market.",
          "The brief was an invitation to the RED Expo. The competition was loud, so we made ours catchy and wrote it as a jingle.",
          "Every Egyptian summer runs on borrowing somebody else's beach chalet keys. We suggested getting your own set."
        ],
        media: [
          {
            type: "video",
            src: "https://player.vimeo.com/video/897539307?h=de26affeff&loop=1&title=0&byline=0&portrait=0",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-01.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-02.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-03.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-04.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-05.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-06.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-07.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-08.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-09.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/red-expo-jingle-ad-10.jpg",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": true
      },
      {
        slug: "canesten-lets-call-it",
        title: "Let's Call It What It Is",
        client: "Canesten",
        category: "Miami Ad School",
        year: "2026",
        image: "Circle_Sticker_Mockup_4.png",
        alt: "Let's Call It What It Is, Canesten",
        sticker: "Never left the deck",
        tagline: "Taboo, rebuilt so nicknames lose.",
        story: [
          "Women do not struggle with the symptoms, they struggle with the words. We whisper, we nickname, down there, the itch, and that avoidance is what keeps people from getting help.",
          "So we hijacked the one game where nicknames are actually illegal. Taboo, rebuilt: say down there, you lose. Say thrush, you score.",
          "Same rule in every market: you cannot treat what you cannot name."
        ],
        media: [
          {
            type: "image",
            src: "Down there.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "pinky toe.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "stickers .jpg",
            caption: "",
            layout: "full"
          },
          {
            type: "image",
            src: "Window Sign Mockup.jpg",
            caption: "",
            layout: "full"
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriters",
            name: "Mohammed Essam, Tiago Lima"
          },
          {
            role: "Art directors",
            name: "Anna Zurabishvili, Maddalena Manchetta"
          },
          {
            role: "Teacher",
            name: "Victor Gonzalez"
          },
          {
            role: "Client",
            name: "Canesten, Miami Ad School Madrid"
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "nivea-never-see-the-sun",
        title: "I Might Never See the Sun Again",
        client: "Nivea",
        category: "Miami Ad School",
        year: "2026",
        image: "live/nivea-i-might-never-see-the-sun-again-cover.jpg",
        alt: "Nivea, I Might Never See the Sun Again",
        sticker: "Never left the deck",
        tagline: "Sunscreen, from the villain's point of view.",
        story: [
          "For years brands sold sunscreen as sun protection. The truth is it was mainly used to hide crimes and to start them. Name one other product that leaves a white mask big enough to make a face unrecognisable, takes forever to rub into a child, causes chaos and starts tears. There is none.",
          "So it was time to end that shady business, and make clear that people who belong to the dark should not benefit from a product designed to expose you to light.",
          "Nivea's new formula: no tears, no white cast, absorbed in seconds. Which were, ironically, the exact reasons it was bad news for some."
        ],
        media: [
          {
            type: "image",
            src: "live/nivea-i-might-never-see-the-sun-again-01.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/nivea-i-might-never-see-the-sun-again-02.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/nivea-i-might-never-see-the-sun-again-03.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/nivea-i-might-never-see-the-sun-again-04.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/nivea-i-might-never-see-the-sun-again-05.jpg",
            caption: ""
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Art",
            name: "Mohammed Essam"
          },
          {
            role: "Teacher",
            name: "Fede Botella"
          },
          {
            role: "Client",
            name: "Nivea, Miami Ad School Madrid"
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "the-mumbled-code",
        title: "Make Their First Words Discount",
        client: "Babyshop",
        category: "Digital activation",
        year: "2025",
        image: "live/uqwyeuoa-random-8-words-cover.jpg",
        alt: "Babyshop, Make Their First Words Discount",
        sticker: "Concept only",
        tagline: "Every toddler keysmash is a promo code.",
        story: [
          "Give a toddler your phone and they will type stringsjksdhsad, or 2m$sdajhad, or kasd@34jksad.",
          "So why not make the chaos count.",
          "Babyshop, through their app, turns any 8-letter toddler smash into a promo code. jklmnopa unlocks an extra 15% off. Making their first words discount."
        ],
        media: [
          {
            type: "video",
            src: "babyshop.mp4",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "oumph-like-any-ad",
        title: "Like Any Ad",
        client: "Oumph!",
        category: "Print",
        year: "2026",
        image: "live/oumph-like-any-ad-cover.jpg",
        alt: "Oumph!, Like Any Ad",
        sticker: "Print, unsold",
        tagline: "A plant burger with nothing to declare.",
        story: [
          "Oumph! is a plant-based burger that tastes and smells like a traditional burger. Apart from the soybeans, there is nothing else setting it apart.",
          "So in this print campaign we made the twist obvious: they will love Oumph! from the first bite, even if it takes a while to notice it is a different kind of burger."
        ],
        media: [
          {
            type: "image",
            src: "live/oumph-like-any-ad-01.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/oumph-like-any-ad-02.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/oumph-like-any-ad-03.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/oumph-like-any-ad-04.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/oumph-like-any-ad-05.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "live/oumph-like-any-ad-06.jpg",
            caption: ""
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriters",
            name: "Mohammed Essam, Jose Pita"
          },
          {
            role: "Teacher",
            name: "Vicente N. Abad"
          },
          {
            role: "Client",
            name: "Oumph!, Miami Ad School"
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": false,
        "ran": false
      },
      {
        slug: "nothing-in-my-dreams",
        title: "Nothing In My Dreams",
        client: "Nothing Phone",
        category: "Experimental",
        year: "2026",
        image: "_ 68.jpeg",
        alt: "Nothing In My Dreams",
        sticker: "Concept only",
        tagline: "A protest against almost everything.",
        story: [
          "Everyone on earth sleeps, and nearly everyone has had the dream where you are running from something and your legs turn to jelly. That is what dreams are actually like. So why do brands keep polishing products and selling them as dream products? Nothing Phone 3 launched #NOTHINGINMYDREAMS, a protest against almost everything."
        ],
        media: [
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": true,
        "ran": false
      },
      {
        slug: "murder-your-thirst",
        title: "Murder What's Next",
        client: "Liquid Death",
        category: "Radio",
        year: "2026",
        image: "",
        alt: "",
        sticker: "Concept only",
        tagline: "",
        story: [],
        media: [
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "image",
            src: "",
            caption: ""
          },
          {
            type: "video",
            src: "",
            caption: ""
          }
        ],
        credits: [
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          },
          {
            role: "",
            name: ""
          }
        ],
        next: {},
        "draft": true,
        "ran": false
      }
    ]
  },
  about: {
    label: "Don't take it personally (it seems so)",
    heading: "A little about me.",
    portrait: "portrait-studio.jpg",
    portraitAlt: "Mohammed Essam",
    paragraphs: [
      "Four years writing for people who skip the ads, and a bunch of other years writing just because I like to. Add to that an entire life having fun being dead serious about making ordinary things look superficially good (my room included).",
      "I am an award-losing copywriter so far. Designed in Egypt, put to work in the UAE, and licensed in Madrid, which makes my buffet of ideas accidentally intercontinental.",
      "I only believe in two things. One, buttlines are just headlines done butt first. And two, he who was born in a city can't be named a farmer. I don't know; I really just needed a second thing."
    ],
    skills: [
      "Big idea development",
      "Brand campaigns",
      "Manipulating",
      "Copywriting",
      "Social & content",
      "Scripting & VO",
      "Concept Development"
    ],
    experience: [
      {
        role: "Senior Copywriter",
        org: "Yango, MENA",
        time: "Jun 2024 – Jul 2025"
      },
      {
        role: "Copywriter",
        org: "Ducklife, Dubai (part-time)",
        time: "Feb 2024 – Jul 2025"
      },
      {
        role: "Copywriter",
        org: "We Are Social, Dubai",
        time: "Jul 2023 – Jun 2024"
      },
      {
        role: "Creative Copywriter",
        org: "Social Nuts, Cairo",
        time: "Feb 2019 – Jun 2023"
      }
    ]
  },
  contact: {
    label: "03 — Get in touch",
    headline: "Have a project? A vacancy?",
    ctaText: "Now we talk.",
    ctaUrl: "mailto:m22essam@gmail.com",
    sub: "",
    resume: {
      label: "Download my Résumé",
      url: "https://drive.google.com/file/d/1kJYJ-WtQAZ9dREIIzsy50wbmkuAPMjFu/view?usp=sharing"
    },
    links: [
      {
        label: "m22essam@gmail.com",
        url: "mailto:m22essam@gmail.com"
      },
      {
        label: "WhatsApp",
        url: "https://wa.me/34685037158"
      },
      {
        label: "LinkedIn",
        url: "https://www.linkedin.com/in/essameldeen/"
      },
      {
        label: "Instagram",
        url: "https://www.instagram.com/essam_93"
      },
      {
        label: "Vimeo",
        url: "https://vimeo.com/essam93"
      }
    ]
  },
  footer: {
    line: "Someone has to win eventually, feel lucky today?",
    linkText: "feel lucky today?",
    linkUrl: "mailto:m22essam@gmail.com"
  },
  layout: {
    desktop: {
      items: [
        {
          slot: "game",
          x: 3.79,
          y: 4.29,
          w: 17.89,
          h: 6.91,
          size: 2.054
        },
        {
          slot: "serial",
          x: 70.7,
          y: 4.29,
          w: 12.06,
          h: 6.91,
          size: 2.054,
          "hidden": true
        },
        {
          slot: "name",
          x: 3.79,
          y: 9.21,
          w: 76.63,
          h: 5.34,
          size: 5.046
        },
        {
          slot: "band",
          x: 81.52,
          y: 4.29,
          w: 15.42,
          h: 4.48,
          size: 2.24
        },
        {
          slot: "badge",
          x: 83.09,
          y: 8.77,
          w: 9.91,
          h: 5.78,
          size: 2.054
        },
        {
          slot: "titleTop",
          x: 3.79,
          y: 23.94,
          w: 92.42,
          h: 17.3,
          size: 17.028
        },
        {
          slot: "titleBottom",
          x: 3.79,
          y: 39.38,
          w: 92.42,
          h: 17.3,
          size: 17.028
        },
        {
          slot: "sub",
          x: 3.81,
          y: 63.42,
          w: 76.61,
          h: 4.95,
          size: 3.174,
          weight: "600"
        },
        {
          slot: "nav0",
          x: 3.79,
          y: 69.92,
          w: 25.2,
          h: 13.69,
          size: 2.705
        },
        {
          slot: "nav1",
          x: 30.1,
          y: 69.92,
          w: 25.11,
          h: 13.69,
          size: 2.705
        },
        {
          slot: "scratchNote",
          x: 56.41,
          y: 64.79,
          w: 25.11,
          h: 2.2,
          size: 1.775,
          weight: "700",
          color: "muted"
        },
        {
          slot: "nav2",
          x: 56.41,
          y: 69.92,
          w: 25.11,
          h: 13.69,
          size: 2.705
        },
        {
          slot: "stamp",
          x: 79.45,
          y: 47.15,
          w: 14.42,
          h: 36.46,
          rotate: 10
        },
        {
          slot: "barcode",
          x: 3.79,
          y: 87.3,
          w: 12.34,
          h: 8.22
        },
        {
          slot: "terms",
          x: 22.02,
          y: 91.41,
          w: 74.19,
          h: 6.22,
          size: 1.9,
          color: "deep"
        },
        {
          type: "box",
          fill: "faint",
          w: 9.55,
          h: 4.6,
          x: 90.18,
          y: 62.39,
          "hidden": true
        },
        {
          type: "text",
          text: "Listen to your gut",
          size: 2.4,
          color: "ink",
          font: "display",
          w: 12.07,
          h: 3.57,
          x: 89.23,
          y: 64.1,
          "hidden": true
        }
      ]
    },
    mobile: {
      items: [
        {
          slot: "game",
          x: 4.86,
          y: 2.77,
          w: 49.88,
          h: 1.66,
          size: 1.015
        },
        {
          slot: "serial",
          x: 61.52,
          y: 2.77,
          w: 33.62,
          h: 1.66,
          size: 1.015
        },
        {
          slot: "name",
          x: 4.86,
          y: 8.58,
          w: 44.62,
          h: 1.66,
          size: 1.583
        },
        {
          slot: "band",
          x: 55.98,
          y: 8.95,
          w: 39.16,
          h: 1.86,
          size: 1.107
        },
        {
          slot: "badge",
          x: 69.98,
          y: 11.53,
          w: 25.16,
          h: 2.84,
          size: 1.015
        },
        {
          slot: "titleTop",
          x: 4.86,
          y: 17.79,
          w: 90.27,
          h: 2.93,
          size: 5.101
        },
        {
          slot: "titleBottom",
          x: 4.86,
          y: 21.54,
          w: 90.27,
          h: 2.93,
          size: 5.101
        },
        {
          slot: "sub",
          x: 4.86,
          y: 26.62,
          w: 90.27,
          h: 5.28,
          size: 1.66
        },
        {
          slot: "nav0",
          x: 4.86,
          y: 33.72,
          w: 90.27,
          h: 8.9,
          size: 1.753
        },
        {
          slot: "nav1",
          x: 4.86,
          y: 43.62,
          w: 90.27,
          h: 8.9,
          size: 1.753
        },
        {
          slot: "scratchNote",
          x: 4.86,
          y: 58.69,
          w: 90.27,
          h: 1.37,
          size: 0.969,
          weight: "700",
          color: "muted"
        },
        {
          slot: "nav2",
          x: 4.86,
          y: 60.95,
          w: 90.27,
          h: 10.67,
          size: 1.753
        },
        {
          slot: "stamp",
          x: 61.68,
          y: 76.5,
          w: 27.77,
          h: 13.37
        },
        {
          slot: "barcode",
          x: 6.75,
          y: 85.81,
          w: 35.68,
          h: 4.06
        },
        {
          slot: "terms",
          x: 4.86,
          y: 93.54,
          w: 90.27,
          h: 4.69,
          size: 0.969
        }
      ]
    }
  }
};
