/* ============================================================
   YOUR SITE'S CONTENT
   Generated by admin.html. Change the text between quotes,
   save, refresh the page.
   ============================================================ */

window.SITE_CONTENT = {
  nav: {
    logo: "mohammed essam.",
    tagline: "(all caps)",
    badge: "available for work copywriter"
  },
  hero: {
    versions: [
      "An [opening] sentence with zero personality, mixed up with a generic portfolio? Hell no. [What] does a CD expect from my [dark], personal work? I'm not a CD, so I can't tell you. All I have goes directly under this section.",
      "[What] does a CD expect from my portfolio? A generic [opening] sentence? Hell no. [Something] with personality, but not overly [dark] and personal? I'm not a CD, so I can't tell you. All I have is the work, and it goes directly under this section.",
      "[Something] with zero personality, mixed up with a [dark], generic [opening] sentence? Hell, that's all I have. [What] does a CD expect from my personal portfolio? I'm not a CD, so I can't tell you. The work goes directly under this section."
    ],
    light: "Wow, it is so bright here! So nice and happy. Let the good light come in to wash away all the dark jokes and bring out big, safe, sunshine smiles. Oh, my CD, I love the day. I love early morning talks. I love making the logo bigger and giving 28 options for a 3-word CTA. I really love working [latenight] for free! All I have is a super happy heart and work that goes right under this section."
  },
  home: {
    dateline: "Creative copywriter · Cairo → Dubai → Madrid → your city?"
  },
  work: {
    heading: "A handpicked selection of my work that are ",
    producedLabel: "Sold and produced",
    presentedLabel: "waiting to be bought",
    produced: [
      {
        slug: "yango-unstoppable-rides",
        title: "Yango — Unstoppable Rides",
        client: "Yango",
        category: "Ride-hailing",
        year: "2025",
        image: "yangocover.jpg",
        alt: "Yango — Unstoppable Rides",
        story: [
          "[Sometimes the city isn't so much in your favor, especially when you’re in a rush or trying to stick to a budget. The Yango super app has a solution for every need, no matter the place.]"
        ],
        media: [],
        credits: [
          {
            role: "Creative Director ",
            name: "Nikita Nikiforov"
          },
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Art Director",
            name: "Hassan AB"
          },
          {
            role: "Production Lead",
            name: "Olesia Starodubtseva"
          }
        ],
        next: {}
      },
      {
        slug: "yango-wedding-rush",
        title: "Yango — The Wedding Rush",
        client: "Yango",
        category: "Ride-hailing",
        year: "2025",
        image: "https://picsum.photos/seed/yango-wedding/1200/900",
        alt: "Yango — The Wedding Rush",
        story: [
          "[Sometimes the city isn't so much in your favor, especially when you’re in a rush or trying to stick to a budget. The Yango super app has a solution for every need, no matter the place.]",
          "[The insight. The thing nobody else noticed.]",
          "[The idea. What we made, and why it answered the insight.]",
          "[The result. A real number if there is one. If there is none, write nothing at all.]"
        ],
        media: [
          {
            type: "image",
            src: "https://picsum.photos/seed/yango-wedding/1600/900",
            caption: "[describe the frame]"
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohamed Essam"
          },
          {
            role: "Agency",
            name: "[agency]"
          },
          {
            role: "Creative Director",
            name: "[name]"
          },
          {
            role: "Art Director",
            name: "[name]"
          }
        ],
        next: {}
      },
      {
        slug: "dominos-true-colors",
        title: "Domino's — The True Colors",
        client: "Domino's",
        category: "QSR",
        year: "2026",
        image: "https://picsum.photos/seed/dominos-colors/1200/900",
        alt: "Domino's — The True Colors",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "pringles-cheesy-cheese",
        title: "Pringles Arabia — Cheesy Cheese",
        client: "Pringles Arabia",
        category: "Snacks",
        year: "2023",
        image: "https://picsum.photos/seed/pringles-cheese/1200/900",
        alt: "Pringles Arabia — Cheesy Cheese",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "nivea-never-see-the-sun",
        title: "Nivea — I Might Never See the Sun Again",
        client: "Nivea",
        category: "Beauty & Care",
        year: "2026",
        image: "https://picsum.photos/seed/nivea-sun/1200/900",
        alt: "Nivea — I Might Never See the Sun Again",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "tuborg-pressure-party",
        title: "Tuborg — The Pressure Party",
        client: "Tuborg",
        category: "Beverage",
        year: "2026",
        image: "https://picsum.photos/seed/tuborg-party/1200/900",
        alt: "Tuborg — The Pressure Party",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "afg-5-star-investment",
        title: "AFG — 5-Star Investment",
        client: "AFG",
        category: "Real estate",
        year: "2023",
        image: "https://picsum.photos/seed/afg-invest/1200/900",
        alt: "AFG — 5-Star Investment",
        story: [
          "Skybridge Tower shook up Egypt's real estate scene by bringing in Cairo's first branded residences tied to a hotel. Our campaign, \"Have your cake and live in it\" was all about helping cautious investors see the perks of jumping into real estate. We used eye-catching visuals and a chill vibe to highlight the financial benefits, and it really resonated with folks in the industry."
        ],
        media: [],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam"
          },
          {
            role: "Creative Director ",
            name: "Aya Elhadad"
          },
          {
            role: "Account Manager",
            name: "Nancy Nabil, Esraa Moharram"
          },
          {
            role: "Agency",
            name: "Social Nuts"
          }
        ],
        next: {
          title: ""
        }
      },
      {
        slug: "rivan-tower-hotel",
        title: "Rivan Tower — The Hotel Is Yours",
        client: "Rivan Tower",
        category: "Real estate",
        year: "2023",
        image: "https://picsum.photos/seed/rivan-tower/1200/900",
        alt: "Rivan Tower — The Hotel Is Yours",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "babyshop-first-words-discount",
        title: "Babyshop — Make Their First Words Discount",
        client: "Babyshop",
        category: "Retail",
        year: "2025",
        image: "https://picsum.photos/seed/babyshop-words/1200/900",
        alt: "Babyshop — Make Their First Words Discount",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "pringles-champions-of-fun",
        title: "Pringles — Champions of Fun",
        client: "Pringles",
        category: "Snacks",
        year: "2024",
        image: "https://picsum.photos/seed/pringles-champions/1200/900",
        alt: "Pringles — Champions of Fun",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "momtaz-cement-chronicles",
        title: "Momtaz Cement — The Chronicles",
        client: "Momtaz Cement",
        category: "Construction",
        year: "2023",
        image: "https://picsum.photos/seed/momtaz-chronicles/1200/900",
        alt: "Momtaz Cement — The Chronicles",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "modon-actors-too-seriously",
        title: "Modon — Sometimes, Actors Take It Too Seriously",
        client: "Modon",
        category: "Real estate",
        year: "2023",
        image: "https://picsum.photos/seed/modon-actors/1200/900",
        alt: "Modon — Sometimes, Actors Take It Too Seriously",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "quarantine-games",
        title: "The Quarantine Games — بنك الحظر",
        client: "",
        category: "Social impact",
        year: "2023",
        image: "https://picsum.photos/seed/quarantine-games/1200/900",
        alt: "The Quarantine Games — بنك الحظر",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "song-for-the-cashless",
        title: "A Song for the Cashless",
        client: "",
        category: "Fintech",
        year: "2022",
        image: "https://picsum.photos/seed/song-cashless/1200/900",
        alt: "A Song for the Cashless",
        story: [],
        media: [],
        credits: [],
        next: {}
      }
    ],
    presented: [
      {
        slug: "pop-the-pressure",
        title: "Tuborg — Pop The Pressure ",
        client: "Tuborg",
        category: "Beverage",
        year: "2026",
        image: "Tuborg project cover.jpg",
        alt: "Tuborg project cover",
        story: [
          "Rising depression and anxiety are holding London's youth back.",
          "To help release the pressure, Tuborg launched a symbolic activation at Glastonbury Festival. During a set by Dave, fans popped thousands of balloons representing real struggles, helping them feel lighter, see clearer, and party responsibly."
        ],
        media: [
          {
            type: "image",
            src: "Tuborg caseboard.jpg",
            caption: ""
          },
          {
            type: "video",
            src: "<div style=\"padding:55.21% 0 0 0;position:relative;\"><iframe src=\"https://player.vimeo.com/video/1218494179?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" style=\"position:absolute;top:0;left:0;width:100%;height:100%;\" title=\"Tuborg - Pop The Pressure\"></iframe></div><script src=\"https://player.vimeo.com/api/player.js\"></script>",
            caption: ""
          },
          {
            type: "image",
            src: "Tuborg wall  mockup.png",
            caption: ""
          },
          {
            type: "image",
            src: "Tuborg Poster Mockup 44.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "Tuborg poster on poster.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "tuborg tote.jpg",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Team",
            name: "Mohammed Essam, Baltazar Lee, Ana Molinero"
          },
          {
            role: "Teacher",
            name: "Pranay Suri"
          },
          {
            role: "Client",
            name: "Tuborg, Miami Ad School Madrid "
          }
        ],
        next: {}
      },
      {
        slug: "oumph-like-any-ad",
        title: "Oumph! — Like Any Ad.",
        client: "Oumph!",
        category: "Food",
        year: "2026",
        image: "https://picsum.photos/seed/oumph-burger/1200/900",
        alt: "Oumph! — Like Any Ad.",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "middle-finger-to-death",
        title: "A Middle Finger to the Death",
        client: "",
        category: "Writing",
        year: "2026",
        image: "https://picsum.photos/seed/middle-finger/1200/900",
        alt: "A Middle Finger to the Death",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "canesteen-lets-call-it",
        title: "Let's Call It What It Is — Canesteen",
        client: "Canesten",
        category: "Health",
        year: "2026",
        image: "Circle_Sticker_Mockup_4.png",
        alt: "Let's Call It What It Is — Canesteen",
        story: [
          "Women don't struggle with symptoms; they struggle with the words. We whisper, we nickname, \"down there,\" \"the itch,\" and that avoidance is what keeps people from getting help.",
          "So we hijacked the one game where nicknames are actually illegal. Taboo, rebuilt: say \"down there,\" you lose. Say \"thrush,\" you score.",
          "We launched it in Brazil and the UAE with the same rule everywhere: you can't treat what you can't name."
        ],
        media: [
          {
            type: "image",
            src: "Down there.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "pinky toe.jpg",
            caption: "",
            layout: "half"
          },
          {
            type: "image",
            src: "stickers .jpg",
            caption: "",
            layout: "full"
          },
          {
            type: "image",
            src: "Window Sign Mockup.jpg",
            caption: "",
            layout: "full"
          }
        ],
        credits: [
          {
            role: "Copywriter",
            name: "Mohammed Essam, Tiago Lima "
          },
          {
            role: "Art Director",
            name: "Anna Zurbashvili, Maddalena Manchetta"
          },
          {
            role: "Teacher",
            name: "Victor Gonzales"
          },
          {
            role: "Client",
            name: "Canesten, Miami Ad School Madrid"
          }
        ],
        next: {}
      },
      {
        slug: "true-colors-of-dominos",
        title: "DOMINO'S - THE TRUE COLORS",
        client: "Domino's",
        category: "Miami Ad School",
        year: "",
        image: "Minimalist Elegant Modern Bold  Advertising Poster Design _ Coffee Shop Branding.jpg",
        alt: "Spec project",
        story: [
          "Walking home at night in heels shouldn’t be a scary experience. To help women feel safer on the streets of London, Domino's decided to show London its true colors with 'slicing-edge' OOH billboards equipped with audio-recognition technology. These billboards detect the sound of accelerating high heels and, once triggered, instantly flash intense red and blue lights, mimicking a police siren to help scare off anyone who might want to cause trouble."
        ],
        media: [
          {
            type: "image",
            src: "Dominos art board.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "Dominos mag 1.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "Dominos art style .jpg",
            caption: ""
          },
          {
            type: "video",
            src: "<div style=\"padding:56.25% 0 0 0;position:relative;\"><iframe src=\"https://player.vimeo.com/video/1205222256?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" style=\"position:absolute;top:0;left:0;width:100%;height:100%;\" title=\"Dominos - The True Color\"></iframe></div><script src=\"https://player.vimeo.com/api/player.js\"></script>",
            caption: ""
          },
          {
            type: "image",
            src: "dominos bus stop poster mockup.jpg",
            caption: ""
          },
          {
            type: "image",
            src: "Dominos news.jpg",
            caption: ""
          }
        ],
        credits: [
          {
            role: "Team ",
            name: "Mohammed Essam, Baltazar Lee,"
          },
          {
            role: "Tutor ",
            name: "Pranay Suri"
          },
          {
            role: "Client",
            name: "Domino's, Miami Ad school Madrid "
          }
        ],
        next: {
          title: "Canesten - Let's Call It What It Is"
        }
      },
      {
        slug: "red-expo-keys",
        title: "Red Expo — Yo Got the Keys",
        client: "Red Expo",
        category: "",
        year: "2024",
        image: "https://picsum.photos/seed/red-expo-keys/1200/900",
        alt: "Red Expo — Yo Got the Keys",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "",
        title: "",
        client: "",
        category: "",
        year: "",
        image: "",
        alt: "",
        story: [],
        media: [],
        credits: [],
        next: {}
      },
      {
        slug: "",
        title: "",
        client: "",
        category: "",
        year: "",
        image: "",
        alt: "",
        story: [],
        media: [],
        credits: [],
        next: {}
      }
    ]
  },
  about: {
    label: "02 — About",
    heading: "A little about me.",
    portrait: "about-photo.jpg",
    portraitAlt: "Mohamed Essam",
    paragraphs: [
      "Four years writing for people who skip the ads, twelve years writing in my drafts, and a whole life having fun being serious about chasing whatever makes ordinary things look good. Award-losing, so far.",
      "Designed in Egypt, put to work in the UAE, licensed in Madrid, which makes my buffet of ideas accidentally intercontinental."
    ],
    skills: [
      "Big idea development",
      "Brand campaigns",
      "Arabic copywriting",
      "Social & content",
      "Script & VO"
    ],
    experience: [
      {
        role: "Senior Copywriter",
        org: "Yango, MENA",
        time: "Jun 2024 – Jul 2025"
      },
      {
        role: "Copywriter",
        org: "Ducklife, Dubai (part-time)",
        time: "Feb 2024 – Jul 2025"
      },
      {
        role: "Copywriter",
        org: "We Are Social, Dubai",
        time: "Jul 2023 – Jun 2024"
      },
      {
        role: "Creative Copywriter",
        org: "Social Nuts, Cairo",
        time: "Feb 2019 – Jun 2023"
      }
    ]
  },
  contact: {
    label: "03 — Get in touch",
    headline: "Have a project? A vacancy?",
    ctaText: "Now we talk.",
    ctaUrl: "mailto:m22essam@gmail.com",
    sub: "",
    resume: {
      label: "Résumé",
      url: ""
    },
    links: [
      {
        label: "m22essam@gmail.com",
        url: "mailto:m22essam@gmail.com"
      },
      {
        label: "WhatsApp",
        url: "https://wa.me/34685037158"
      },
      {
        label: "LinkedIn",
        url: "https://www.linkedin.com/in/essameldeen/"
      },
      {
        label: "Instagram",
        url: "https://www.instagram.com/essam_93"
      },
      {
        label: "Vimeo",
        url: "https://vimeo.com/essam93"
      }
    ]
  },
  footer: {
    line: "© 2026 · Written by luck. Copywriters reserved, I know.",
    mark: "MOHAMED ESSAM PG-13",
    joke: "for the jokes in this portfolio."
  }
};
